// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  sidebar: [
    "welcome-to-pear",
    {
      type: "category",
      label: "About Pear",
      link: { type: "doc", id: "about-pear/what-is-pear" },
      items: [
        "about-pear/what-is-pear",
        {
          type: "category",
          label: "Architecture & Tooling",
          items: [
            "about-pear/architecture/index",
            "about-pear/architecture/building-blocks",
            "about-pear/architecture/helpers",
            "about-pear/architecture/tools",
          ],
        },
        "about-pear/use-cases",
        "about-pear/apps-built-with-pear",
        "about-pear/faq",
      ],
    },

    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/install",
        "getting-started/setup",
        "getting-started/simple-chat-app",
        "getting-started/release",
        "getting-started/share",
        "getting-started/best-practices",
      ],
    },

    {
      type: "category",
      label: "How To",
      link: { type: "doc", id: "how-to/index" },
      items: [

        {
          type: "category",
          label: "Create a Terminal App",
          items: [
            "how-to/terminal/setup",
            "how-to/terminal/simple-chat-app",
            "how-to/terminal/debug",
          ],
        },
        {
          type: "category",
          label: "Manage Installed Apps",
          items: [
            "how-to/manage-installed-apps/list-installed-pear-apps",
            "how-to/manage-installed-apps/uninstall-a-pear-app",
          ],
        },
        {
          type: "category",
          label: "Connect to Peers",
          items: [
            "how-to/connect-to-peers/connect-two-pears-with-hyper-dht",
            "how-to/connect-to-peers/connect-many-pears-with-hyper-swarm",
          ],
        },
        {
          type: "category",
          label: "Replicate and Persist Data",
          items: [
            "how-to/replicate-and-persist-data/replicate-and-persist-with-hyper-core",
            "how-to/replicate-and-persist-data/manage-multiple-hypercores-with-corestore",
            "how-to/replicate-and-persist-data/share-append-only-databases-with-hyperbee",
            "how-to/replicate-and-persist-data/create-a-full-peer-to-peer-filesystem-with-hyperdrive",
          ],
        },
        {
          type: "category",
          label: "Create Mobile Apps",
          items: [
            "how-to/create-mobile-apps/create-a-bare-mobile-app",
            "how-to/create-mobile-apps/bare-on-mobile",
          ],
        },
        "how-to/create-a-pear-init-template",
        "how-to/migrate-from-pear-v1-to-v2",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        'tutorials/create-a-chat-app',
        'tutorials/create-a-discord-clone',
        'tutorials/create-a-private-game-server',
        "tutorials/create-a-todo-app",
      ],
    },
    {
      type: "category",
      label: "References",
      link: { type: "doc", id: "references/index" },
      items: [
        {
          type: "category",
          label: "Pear",
          link: { type: "doc", id: "references/pear/overview" },
          items: [{ type: "autogenerated", dirName: "references/pear" }],
        },
        {
          type: "category",
          label: "Bare",
          link: { type: "doc", id: "references/bare/overview" },
          items: [{ type: "autogenerated", dirName: "references/bare" }],
        },
        {
          type: "category",
          label: "Building Blocks",
          link: { type: "doc", id: "references/building-blocks/overview" },
          items: [
            { type: "autogenerated", dirName: "references/building-blocks" },
          ],
        },
        {
          type: "category",
          label: "Helpers",
          link: { type: "doc", id: "references/helpers/overview" },
          items: [{ type: "autogenerated", dirName: "references/helpers" }],
        },
        {
          type: "category",
          label: "Tools",
          link: { type: "doc", id: "references/tools/overview" },
          items: [{ type: "autogenerated", dirName: "references/tools" }],
        },
      ],
    },
    "troubleshooting",
  ],
};

export default sidebars;
