// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    "welcome-to-pear",
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/install",
        {
          type: "category",
          label: "Create a Terminal App",
          items: [
            "getting-started/terminal/setup",
            "getting-started/terminal/simple-chat-app",
            "getting-started/terminal/debug",
          ],
        },
        {
          type: "category",
          label: "Create a Desktop App",
          items: [
            "getting-started/desktop/setup",
            "getting-started/desktop/simple-chat-app",
          ],
        },
        "getting-started/release",
        "getting-started/share",
        "getting-started/best-practices",
      ],
    },

    {
      type: "category",
      label: "How To",
      items: [
        "how-to/connect-two-pears-with-hyper-dht",
        "how-to/connect-many-pears-with-hyper-swarm",
        "how-to/replicate-and-persist-with-hyper-core",
        "how-to/manage-multiple-hypercores-with-corestore",
        "how-to/create-a-full-peer-to-peer-filesystem-with-hyperdrive",
        "how-to/create-a-bare-mobile-app",
        "how-to/migrate-from-pear-v1-to-v2",
      ],
    },
    {
      type: "category",
      label: "References",
      items: [
        {
          type: "category",
          label: "Bare",
          items: [{ type: "autogenerated", dirName: "references/bare" }],
        },
        {
          type: "category",
          label: "Pear",
          items: [{ type: "autogenerated", dirName: "references/pear" }],
        },
        {
          type: "category",
          label: "Building Blocks",
          items: [{ type: "autogenerated", dirName: "references/helpers" }],
        },
        {
          type: "category",
          label: "Helpers",
          items: [{ type: "autogenerated", dirName: "references/helpers" }],
        },
        {
          type: "category",
          label: "Tools",
          items: [{ type: "autogenerated", dirName: "references/tools" }],
        },
      ],
    },
    'faq',
    'troubleshooting'
  ],
};

export default sidebars;
